/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#e1e2ed',
        'on-tertiary-container': '#ffede6',
        'on-primary-fixed-variant': '#003ea8',
        'on-error': '#ffffff',
        'on-primary': '#ffffff',
        'primary-container': '#2563eb',
        'surface-container-lowest': '#ffffff',
        'on-secondary': '#ffffff',
        tertiary: '#943700',
        'secondary-fixed-dim': '#b7c4ff',
        'surface-bright': '#faf8ff',
        'surface-variant': '#e1e2ed',
        'on-tertiary-fixed': '#360f00',
        'on-surface': '#191b23',
        'on-tertiary-fixed-variant': '#7d2d00',
        'primary-fixed': '#dbe1ff',
        secondary: '#1d4ed8',
        'tertiary-container': '#bc4800',
        'on-surface-variant': '#434655',
        surface: '#faf8ff',
        'surface-container': '#ededf9',
        'on-secondary-container': '#fffbff',
        background: '#faf8ff',
        'inverse-surface': '#2e3039',
        'on-secondary-fixed': '#001551',
        'surface-tint': '#0053db',
        'on-background': '#191b23',
        'on-tertiary': '#ffffff',
        error: '#ba1a1a',
        'inverse-primary': '#b4c5ff',
        'on-primary-fixed': '#00174b',
        'surface-dim': '#d9d9e5',
        outline: '#737686',
        'surface-container-low': '#f3f3fe',
        'surface-container-high': '#e7e7f3',
        'secondary-fixed': '#dce1ff',
        'on-secondary-fixed-variant': '#0039b5',
        'error-container': '#ffdad6',
        'on-primary-container': '#eeefff',
        'primary-fixed-dim': '#b4c5ff',
        'secondary-container': '#4069f2',
        primary: '#004ac6',
        'on-error-container': '#93000a',
        'inverse-on-surface': '#f0f0fb',
        'outline-variant': '#c3c6d7',
        'tertiary-fixed-dim': '#ffb596',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xl: '32px',
        sm: '8px',
        gutter: '24px',
        xs: '4px',
        lg: '24px',
        margin: '32px',
        'container-max': '1440px',
        '3xl': '64px',
        md: '16px',
        '2xl': '48px',
        unit: '4px',
      },
      fontFamily: {
        h1: ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        h2: ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        h3: ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'display-xl': ['Inter', 'sans-serif'],
      },
      fontSize: {
        h1: ['30px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1', letterSpacing: '0.01em', fontWeight: '600' }],
        h2: ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.02em', fontWeight: '500' }],
        h3: ['20px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '600' }],
        'display-lg': ['36px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
