import { useCallback, useEffect, useMemo, useState } from 'react'
import { useAuth } from '../auth/authState'

const Field = ({ label, value, onChange, placeholder }) => <label className="block text-xs font-bold uppercase tracking-wide text-slate-500">{label}<input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-normal normal-case tracking-normal outline-none focus:border-blue-500" /></label>

export default function DoctorEHRWorkspace() {
  const { request } = useAuth(); const [patients, setPatients] = useState([]); const [selectedId, setSelectedId] = useState(''); const [record, setRecord] = useState(null); const [encounterId, setEncounterId] = useState(''); const [message, setMessage] = useState(''); const [form, setForm] = useState({ note: '', diagnosis: '', medicine: '', dosage: '', frequency: '', duration: '' })
  useEffect(() => { request('/api/v1/doctors/me/patients').then((data) => { setPatients(data); if (data[0]) setSelectedId((current) => current || data[0].patient_profile_id) }).catch((error) => setMessage(error.message)) }, [request])
  const refreshRecord = useCallback(() => { if (!selectedId) return Promise.resolve(); return request(`/api/v1/doctors/me/patients/${selectedId}`).then((data) => { setRecord(data); setEncounterId(data.encounters[0]?.id || '') }) }, [selectedId, request])
  useEffect(() => { if (!selectedId) return; request(`/api/v1/doctors/me/patients/${selectedId}`).then((data) => { setRecord(data); setEncounterId(data.encounters[0]?.id || '') }).catch((error) => setMessage(error.message)) }, [selectedId, request])
  const appointment = useMemo(() => record?.appointments?.[0], [record])
  const createEncounter = async () => { if (!appointment) return setMessage('This patient has no assigned appointment to start from.'); const data = await request('/api/v1/doctors/me/encounters', { method: 'POST', body: JSON.stringify({ patient_id: selectedId, appointment_id: appointment.id, encounter_type: 'outpatient', chief_complaint: 'Scheduled consultation', reason: 'Consultation initiated by assigned doctor' }) }); setEncounterId(data.id); setMessage('Encounter started.'); await refreshRecord() }
  const saveNote = async () => { await request(`/api/v1/doctors/me/encounters/${encounterId}`, { method: 'PATCH', body: JSON.stringify({ clinical_notes: form.note, reason: 'Clinical note recorded during consultation' }) }); setMessage('Encounter note saved with immutable history.'); await refreshRecord() }
  const addDiagnosis = async () => { await request(`/api/v1/doctors/me/encounters/${encounterId}/diagnoses`, { method: 'POST', body: JSON.stringify({ description: form.diagnosis, review_status: 'confirmed', reason: 'Diagnosis recorded from consultation findings' }) }); setMessage('Diagnosis recorded.'); await refreshRecord() }
  const addPrescription = async () => { await request(`/api/v1/doctors/me/encounters/${encounterId}/prescriptions`, { method: 'POST', body: JSON.stringify({ medicine: form.medicine, dosage: form.dosage, frequency: form.frequency, duration: form.duration, reason: 'Medication prescribed during consultation' }) }); setMessage('Prescription recorded.'); await refreshRecord() }
  return <section className="min-h-screen bg-slate-50 px-6 pb-16 pt-28"><div className="mx-auto max-w-7xl"><div className="mb-6"><p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-700">Clinical workspace</p><h1 className="text-3xl font-extrabold text-slate-900">Authorized patients</h1><p className="mt-2 text-sm text-slate-600">Only patients linked through your appointment, token, or encounter assignments appear here.</p></div>{message && <div className="mb-4 rounded-xl bg-blue-50 p-3 text-sm text-blue-800">{message}</div>}
    <div className="grid gap-5 lg:grid-cols-[300px_1fr]"><aside className="rounded-2xl border border-blue-100 bg-white p-3">{patients.length ? patients.map((patient) => <button key={patient.patient_profile_id} onClick={() => setSelectedId(patient.patient_profile_id)} className={`mb-2 w-full rounded-xl p-4 text-left ${selectedId === patient.patient_profile_id ? 'bg-blue-700 text-white' : 'bg-slate-50 text-slate-800'}`}><strong className="block">{patient.name}</strong><span className="text-xs opacity-75">{patient.medical_record_number}</span></button>) : <p className="p-4 text-sm text-slate-500">No authorized patients.</p>}</aside>
      <main className="space-y-5">{record && <><section className="rounded-2xl border border-blue-100 bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-extrabold">{record.patient.name}</h2><p className="text-sm text-slate-500">{record.patient.medical_record_number} · {record.patient.age ?? 'Age unknown'} years</p></div>{!encounterId && <button onClick={createEncounter} className="rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-bold text-white">Start encounter</button>}</div><div className="mt-5 grid gap-3 md:grid-cols-3"><div className="rounded-xl bg-red-50 p-4"><strong>{record.allergies.length}</strong><p className="text-xs text-red-700">Active allergies</p></div><div className="rounded-xl bg-blue-50 p-4"><strong>{record.encounters.length}</strong><p className="text-xs text-blue-700">Encounters</p></div><div className="rounded-xl bg-emerald-50 p-4"><strong>{record.prescriptions.length}</strong><p className="text-xs text-emerald-700">Prescriptions</p></div></div></section>
        {encounterId && <section className="grid gap-5 xl:grid-cols-3"><div className="rounded-2xl border border-blue-100 bg-white p-5"><h3 className="mb-4 font-extrabold">Encounter note</h3><textarea value={form.note} onChange={(event) => setForm({ ...form, note: event.target.value })} className="h-36 w-full rounded-xl border border-slate-200 p-3 text-sm" placeholder="Clinical observations and plan" /><button onClick={saveNote} disabled={!form.note} className="mt-3 w-full rounded-xl bg-blue-700 py-2.5 text-sm font-bold text-white disabled:opacity-40">Save note</button></div><div className="rounded-2xl border border-blue-100 bg-white p-5"><h3 className="mb-4 font-extrabold">Diagnosis</h3><Field label="Description" value={form.diagnosis} onChange={(value) => setForm({ ...form, diagnosis: value })} placeholder="Confirmed clinical diagnosis" /><button onClick={addDiagnosis} disabled={!form.diagnosis} className="mt-3 w-full rounded-xl bg-blue-700 py-2.5 text-sm font-bold text-white disabled:opacity-40">Add diagnosis</button></div><div className="rounded-2xl border border-blue-100 bg-white p-5"><h3 className="mb-4 font-extrabold">Prescription</h3><div className="space-y-3"><Field label="Medicine" value={form.medicine} onChange={(value) => setForm({ ...form, medicine: value })} /><Field label="Dosage" value={form.dosage} onChange={(value) => setForm({ ...form, dosage: value })} /><Field label="Frequency" value={form.frequency} onChange={(value) => setForm({ ...form, frequency: value })} /><Field label="Duration" value={form.duration} onChange={(value) => setForm({ ...form, duration: value })} /></div><button onClick={addPrescription} disabled={!form.medicine || !form.dosage || !form.frequency || !form.duration} className="mt-3 w-full rounded-xl bg-blue-700 py-2.5 text-sm font-bold text-white disabled:opacity-40">Add prescription</button></div></section>}
      </>}</main></div>
  </div></section>
}
