"""initial PostgreSQL foundation schema

Revision ID: 675b1b7dc8a2
Revises: 
Create Date: 2026-07-11 23:40:08.440494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675b1b7dc8a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('hospital_name', sa.String(length=160), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('total_doctors', sa.Integer(), nullable=False),
    sa.Column('emergency_available', sa.String(length=16), nullable=False),
    sa.Column('avg_wait_time', sa.Integer(), nullable=False),
    sa.Column('busyness_level', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('hospital_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('age IS NULL OR (age >= 0 AND age <= 130)', name='ck_users_age'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('departments',
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('dept_name', sa.String(length=120), nullable=False),
    sa.Column('avg_consult_time', sa.Integer(), nullable=False),
    sa.CheckConstraint('avg_consult_time > 0', name='ck_department_consult_time'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dept_id'),
    sa.UniqueConstraint('hospital_id', 'dept_name', name='uq_department_hospital_name')
    )
    op.create_table('feedback',
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_feedback_rating'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_table('symptoms_history',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('severity_score', sa.Integer(), nullable=True),
    sa.Column('predicted_department', sa.String(length=120), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('doctors',
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('doctor_name', sa.String(length=120), nullable=False),
    sa.Column('specialization', sa.String(length=120), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('patients_today', sa.Integer(), nullable=False),
    sa.Column('availability', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doctor_id')
    )
    op.create_table('queue_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('total_patients', sa.Integer(), nullable=False),
    sa.Column('avg_wait_time', sa.Integer(), nullable=False),
    sa.Column('peak_hour', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('ix_queue_logs_dept_date', 'queue_logs', ['dept_id', 'log_date'], unique=False)
    op.create_table('queue_sessions',
    sa.Column('queue_session_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('queue_date', sa.Date(), nullable=False),
    sa.Column('next_sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('next_sequence > 0', name='ck_queue_session_sequence'),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('queue_session_id'),
    sa.UniqueConstraint('hospital_id', 'dept_id', 'queue_date', name='uq_queue_session_day')
    )
    op.create_table('appointments',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('appointment_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_table('tokens',
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('queue_session_id', sa.Integer(), nullable=False),
    sa.Column('queue_date', sa.Date(), nullable=False),
    sa.Column('token_number', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('priority', sa.String(length=24), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('estimated_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("priority IN ('normal','elderly','emergency')", name='ck_token_priority'),
    sa.CheckConstraint("status IN ('waiting','serving','completed','missed','cancelled')", name='ck_token_status'),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['queue_session_id'], ['queue_sessions.queue_session_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('hospital_id', 'dept_id', 'queue_date', 'token_number', name='uq_token_queue_number')
    )
    op.create_index('ix_tokens_dept_status_created', 'tokens', ['dept_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_tokens_hospital_status', 'tokens', ['hospital_id', 'status'], unique=False)
    op.create_index('ix_tokens_queue_priority', 'tokens', ['queue_session_id', 'status', 'priority', 'created_at'], unique=False)
    op.create_table('emergency_cases',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('emergency_level', sa.String(length=32), nullable=False),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.Column('admitted', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.token_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emergency_cases')
    op.drop_index('ix_tokens_queue_priority', table_name='tokens')
    op.drop_index('ix_tokens_hospital_status', table_name='tokens')
    op.drop_index('ix_tokens_dept_status_created', table_name='tokens')
    op.drop_table('tokens')
    op.drop_table('appointments')
    op.drop_table('queue_sessions')
    op.drop_index('ix_queue_logs_dept_date', table_name='queue_logs')
    op.drop_table('queue_logs')
    op.drop_table('doctors')
    op.drop_table('symptoms_history')
    op.drop_table('feedback')
    op.drop_table('departments')
    op.drop_table('users')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
