"""add idempotency and audit events

Revision ID: b3d56a65a637
Revises: 675b1b7dc8a2
Create Date: 2026-07-12 00:15:23.399209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d56a65a637'
down_revision = '675b1b7dc8a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_records',
    sa.Column('idempotency_record_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('scope', sa.String(length=80), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_record_id'),
    sa.UniqueConstraint('scope', 'key', name='uq_idempotency_scope_key')
    )
    op.create_index('ix_idempotency_expires_at', 'idempotency_records', ['expires_at'], unique=False)
    op.create_table('audit_events',
    sa.Column('audit_event_id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=160), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('remote_addr', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("outcome IN ('success','denied','failure')", name='ck_audit_event_outcome'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('audit_event_id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('ix_audit_events_actor', 'audit_events', ['actor_user_id', 'created_at'], unique=False)
    op.create_index('ix_audit_events_created_at', 'audit_events', ['created_at'], unique=False)
    op.create_index('ix_audit_events_resource', 'audit_events', ['resource_type', 'resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_events_resource', table_name='audit_events')
    op.drop_index('ix_audit_events_created_at', table_name='audit_events')
    op.drop_index('ix_audit_events_actor', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_idempotency_expires_at', table_name='idempotency_records')
    op.drop_table('idempotency_records')
    # ### end Alembic commands ###
